#By Category
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX scovo: <http://purl.org/NET/scovo#> 
PREFIX void: <http://rdfs.org/ns/void#> 
PREFIX : <http://example.org/void-example#> 

SELECT DISTINCT ?dataset
FROM <http://void-impl.googlecode.com/svn/trunk/guide/void.ttl>
WHERE {
  ?dataset a void:Dataset .
  ?dataset dcterms:subject <http://dbpedia.org/resource/Computer_science> .
}